data:
  json_root: "/home/cse/Desktop/zahin_thesis_work/My_Thesis_Repo/rearrange/dataset_json"
  dataset_name: "FaceForensics++"

model:
  model_path: "/home/cse/Desktop/zahin_thesis_work/My_Thesis_Repo/models/model6.py"   # ← change to your fused model file
  model_class: "FusedModel"
  vit_name: "dinov2_vits14"
  vit_weight: null

  # Graph path hyperparameters
  num_gcn_layers: 3
  num_clusters: 512          # MinCut pooling target
  num_transformer_blocks: 3  # for the graph transformer
  num_heads: 8
  mlp_dim: 512
  dropout: 0.2

training:
  epochs: 50
  batch_size: 6
  lr: 0.0001
  vit_lr: 0.00001
  optimizer: "AdamW"
  weight_decay: 0.0001
  num_frames: 8

  # New loss settings
  focal_gamma: 2.0      # higher = harder examples get more weight
  mincut_weight: 0.1
  ortho_weight: 0.01

paths:
  checkpoint_dir: "/home/cse/Desktop/zahin_thesis_work/My_Thesis_Repo/checkpoints"
  log_dir: "/home/cse/Desktop/zahin_thesis_work/My_Thesis_Repo/logs"

early_stopping:
  patience: 5
  delta: 0.0005

seed: 42
device: "cuda"
resume: false