data:
  json_root: "/home/zahin/Desktop/My_Thesis_Repo/rearrange/dataset_json"
  dataset_name: "FaceForensics++"

model:
  vit_name: "dinov2_vits14"
  pretrained_path: null # set to a .pth path if you want to load weights

training:
  epochs: 1
  batch_size: 4
  lr: 0.0001
  optimizer: "Adam"
  weight_decay: 0.00001
  num_frames: 8
  knn_k: 8

paths:
  checkpoint_dir: "/home/zahin/Desktop/My_Thesis_Repo/checkpoints"
  log_dir: "/home/zahin/Desktop/My_Thesis_Repo/logs"

early_stopping:
  patience: 3
  delta: 0.001

seed: 42
device: "cpu"
resume: false # set true to resume from last_checkpoint.pth
